apiVersion: v1
kind: Pod
metadata:
  name: t2-htpm-t0
spec:
  hostname: power-server
  containers:
  - name: t2-htpm-t0
    image: sjc.vultrcr.com/hacktheplanet/t2-htpm-t0
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]

  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets:
  - name: regcred
