apiVersion: v1
kind: Pod
metadata:
  name: t2-htpm-d2
spec:
  hostname: andreas-desktop
  containers:
  - name: t2-htpm-d2
    image: sjc.vultrcr.com/hacktheplanet/t2-htpm-d2
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]

  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets:
  - name: regcred
